### PR TITLE
Added support for setting environment variables in the `pipeline-spec.yaml`

### LINKED ISSUE #177: Ability to preserve missingValues in dump
Passing this on to you @roll as I think it will be a pretty big change across multiple repos that will require your codebase knowledge. See previous discussion here: https://github.com/BCODMO/frictionless-usecases/issues/32 as well as previous PRs here: https://github.com/frictionlessdata/tableschema-py/pull/260, https://github.com/frictionlessdata/datapackage-pipelines/pull/175, https://github.com/datahq/dataflows/pull/119.

Sometimes missingValues have meaning beyond "no measurement taken", and sometimes one field will have multiple different kinds of missingValues (such as no measurement taken, measurement below threshold, etc). It's very important that we be able to preserve that data, and up until now we are usually just keeping the field as a string type even though it is clearly a number. It would be great if there was an option to dump_to_path, or a different kind of missingValue parameter, that would show the missingValues properly after the dump.

Solution thoughts:
- update all processors to check if the value is in the missingValues parameter before doing any kind of processing. If in the missingValue list, continue. [probably way too much work]
- create some kind of data type that is interpreted as None by all of the processors but dump_to_path can see it and extract the original value. During the load step instead of setting the fields where there are missingValues to None, set the field to this object (and store the original data in it).

(this is highest priority for us right now I believe)

### LINKED ISSUE #181: Ability to set environment variables for a pipeline
# Overview

Recently, I've added support for `TABLESCHEMA_PRESERVE_MISSING_VALUES` env var to `tableschema-py` - https://github.com/frictionlessdata/tableschema-py#experimental - which can be useful for some use cases.

I propose we have a standard way to declare environment variables for a pipeline as it implemented for many other declarative formats like `docker-compose.yml`, `travis.yml`, etc

So we can have something like this:

```yml
temporal:
  title: temporal
  description: "temporal format"
  enviroment:
    DEBUG: True
  pipeline:

  - run: load
    parameters:
      from: 'temporal.csv'
      override_fields:
        date:
          outputFormat: '%m/%d/%Y'

  - run: dump_to_path
    parameters:
      out-path: 'output'
      pretty-descriptor: true
      temporal_format_property: outputFormat
```

### PR DESCRIPTION
**Pull request by roll**
- fixes #177
- fixes #181

### CODE REVIEW

**Comment by roll** [comment]
Hi @akariv @cschloer,

It's an initial implementation. It works but probably slightly naive. Please take a look.

**Comment by cschloer** [comment]
looks great to me!

**Comment by roll** [comment]
Hi @akariv,

It's ready for a review

**Comment by cschloer** [comment]
Any thoughts here @akariv ?

**Comment by roll** [comment]
Hi @akariv, rebased to fix the test :+1:

**Comment by roll** [comment]
Hi @akariv, could you please take a look - the tests are fixed

**Comment by roll** [comment]
Thank you!

**Pull request merged**
