### PR TITLE
added test pipeline that causes huge RAM consumption

### PR DESCRIPTION
**Pull request by OriHoch**
screenshot from 2018-03-06 18-40-14

(this PR includes the commits from #123 because both depend on a change to test_main for better output of failures)

### CODE REVIEW

**Comment by akariv** [comment]
This is the culprit for the memory problem I think:
https://github.com/frictionlessdata/datapackage-py/blob/master/datapackage/package.py#L438

The entire ZIP file is loaded into memory for inspection.
I will open a pull request to fix this issue.

**Comment by OriHoch** [comment]
the zip file is only 12mb

the leak fills up GBs in seconds

**Comment by akariv** [comment]
Okay, will rethink :)

**Comment by OriHoch** [comment]
fixed

**Comment by OriHoch** [comment]
quite an annoying waste of time.. but a very good learning experience :+1:

**Pull request closed without merging**
