### PR TITLE
Add duplicate_to_end parameter

### PR DESCRIPTION
**Pull request by cschloer**
Following the PR here: https://github.com/datahq/dataflows/pull/156

### CODE REVIEW

**Comment by cschloer** [comment]
@roll

**Comment by akariv** [comment]
Looks good - just need to also bump dataflows version when it's released.

**Comment by cschloer** [comment]
Dataflows version bumped!

**Comment by cschloer** [comment]
Bumping this @akariv

**Comment by akariv** [comment]
Sorry for the delay

**Review by akariv — COMMENTED** [review]
lgtm

**Comment by akariv** [comment]
https://pypi.org/project/datapackage-pipelines/2.2.6/

**Comment by cschloer** [comment]
no worries for the delay! Thanks for the merge.

**Pull request merged**
