### PR TITLE
add support for using the fixture tests from other libraries

### PR DESCRIPTION
**Pull request by OriHoch**
* [x] I've added tests to cover the proposed changes

## overview
In [budgetkey-data-pipelines](https://github.com/OpenBudget/budgetkey-data-pipelines) project we have the need to write unit tests for custom datapackage processors

The framework used to test the datapackage pipelines stdlib is perfectly suited for that.

## Changes proposed in this pull request:

- refactor the test_stdlib code into an externally accessible base class under datapackage_pipelines.utilities.lib_test_helpers.ProcessorFixtureTestsBase
- test_stdlib was modified to use this class

### CODE REVIEW

**Comment by brew** [comment]
@OriHoch Would you mind giving a brief guide to using this text fixture set up in an external plugin? I'm trying to get a simple example working, but I'm not sure how to structure the fixtures or `ProcessorFixtureTestsBase` subclass.

**Comment by OriHoch** [comment]
@brew - it's used here: https://github.com/frictionlessdata/datapackage-pipelines/tree/master/tests/stdlib
and here: https://github.com/OriHoch/budgetkey-data-pipelines/tree/7526219c0bc8420a9e595e3899df01e7f6c59d85/tests/tenders

**Comment by brew** [comment]
Thanks - I found those. I was more interested what each item (delimited by '--') in the fixtures file refers to. They're order dependent, but not documented, so a bit opaque (to me).

**Comment by OriHoch** [comment]
this is the relevant function:
https://github.com/frictionlessdata/datapackage-pipelines/blob/master/datapackage_pipelines/utilities/lib_test_helpers.py#L47

the order is:
```
processor - the name of the processor to run
--
params - json object with parameters for the processor
--
dp_in - input datapackage descriptor
--
data_in - input data stream
--
dp_out - expected output datapackage descriptor
--
data_out - expected output data stream
```

**Comment by brew** [comment]
Thanks - that's a useful summary. Especially for people coming back to this pull request later.

**Pull request merged**
