### PR TITLE
support exclusion of directories from scanning for pipeline specs

### PR DESCRIPTION
**Pull request by OriHoch**
All sub-directories are scanned for pipeline-specs, this is not optimal, especially with data directories contained under the project root directory.

Added support for exclusion of directory patterns (glob), by default, excluding `.*` directories and allowing to exclude additional patterns.

Uses os.walk support for modifying the directories that will be scanned by modifying the dirnames list in-place.

See updated README for usage details

### CODE REVIEW

**Comment by brew** [comment]
Could this support an ignore file (like .dockerignore, .gitignore etc)? Perhaps `.dpp_spec_ignore`? Files to ignore seems like something you'd always want to do for all installations of a project, rather than something to configure for a specific installation in an env var.

**Comment by OriHoch** [comment]
updated to use .dpp_spec_ignore file

**Comment by akariv** [comment]
@OriHoch can you please check why ci is failing?

**Comment by OriHoch** [comment]
@akariv fixed

**Pull request merged**
